-- 1. People Table (Sourced primarily from people.csv)
CREATE TABLE People (
    identifier TEXT PRIMARY KEY,
    name TEXT,
    unique_name TEXT,
    key_bcci TEXT,
    key_bcci_2 TEXT,
    key_bigbash TEXT,
    key_cricbuzz TEXT,
    key_cricheroes TEXT,
    key_crichq TEXT,
    key_cricinfo TEXT,
    key_cricinfo_2 TEXT,
    key_cricinfo_3 TEXT,
    key_cricingif TEXT,
    key_cricketarchive TEXT,
    key_cricketarchive_2 TEXT,
    key_cricketworld TEXT,
    key_nvplay TEXT,
    key_nvplay_2 TEXT,
    key_opta TEXT,
    key_opta_2 TEXT,
    key_pulse TEXT,
    key_pulse_2 TEXT
);